Updated NetworkDevice and constructors to have and take a new variabl…
nnickodem/NetworkDomination pull request #66
Opened 2019-03-06 18:53 UTC by T0YMAK3R

…e, Integer index, which will be used for building an adjacency matrix for determining shortest path with Dijstra alg.

2019-03-06 18:58 UTC, nnickodem requested changes

2019-03-06 18:58 UTC, nnickodem commented on src/main/java/Objects/GameLevel.java
> +import java.util.Iterator;
unused imports

2019-03-06 18:58 UTC, nnickodem commented on src/main/java/Objects/NetworkDevices/NetworkDevice.java
> +    private Integer index;
no getter method?

2019-03-09 01:03 UTC, T0YMAK3R commented on src/main/java/Objects/GameLevel.java
> +import java.util.Iterator;
Unused imports removed.

2019-03-09 01:03 UTC, T0YMAK3R commented on src/main/java/Objects/NetworkDevices/NetworkDevice.java
> +    private Integer index;
Created getter for the index.

2019-03-09 01:19 UTC, nnickodem submitted a review, later dismissed

2019-03-09 02:25 UTC, nnickodem approved these changes

2019-03-09 02:25 UTC, merged